server:
  port: 8080

qiniu:
  accessKey:
  secretKey:
  bucket:
  domain:



jwt:
  secret: test
  sessionTime: 84000


spring:
  http:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB
  devtools:
    restart:
      enabled: true
  datasource:
  #数据库设置
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/doraro_blog?useSSL=false&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall, log4j
#      web-stat-filter:
#              url-pattern: /*
#              exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      #监控登录设置
      stat-view-servlet:
        allow: 127.0.0.1
        login-username:
        login-password:


mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.doraro.model.*
    configuration:
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        field-strategy: not_empty
        db-type: mysql
        id-type: uuid


